from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from dual_engine.auto_features import generate_auto_features
from dual_engine.composite_features import build_composite_features, composite_specs_frame
from dual_engine.config import AutoFeatureConfig, EnginePaths
from dual_engine.semantic_features import generate_semantic_features


def run_candidate_pool(sample_size: int = 3000, max_depth: int = 2) -> dict:
    paths = EnginePaths()
    candidate_dir = paths.candidate_dir
    auto_dir = candidate_dir / "auto"
    semantic_dir = candidate_dir / "semantic"
    registry_dir = candidate_dir / "registry"
    for directory in [candidate_dir, auto_dir, semantic_dir, registry_dir]:
        directory.mkdir(parents=True, exist_ok=True)

    auto_result = generate_auto_features(
        config=AutoFeatureConfig(sample_size=sample_size, max_depth=max_depth),
        output_dir=auto_dir,
    )
    semantic_result = generate_semantic_features(paths=paths, output_dir=semantic_dir)

    auto_frame = auto_result.feature_matrix.copy()
    semantic_frame = semantic_result.feature_matrix.copy()
    semantic_merge = semantic_frame.drop(columns=["TARGET"], errors="ignore")

    merged = auto_frame.merge(semantic_merge, on="SK_ID_CURR", how="left")
    composite = build_composite_features(merged)
    merged = merged.merge(composite, on="SK_ID_CURR", how="left")

    merged.to_parquet(candidate_dir / "candidate_pool.parquet", index=False)
    composite_specs = composite_specs_frame()
    composite_specs.to_csv(registry_dir / "composite_feature_spec.csv", index=False)

    auto_registry = pd.DataFrame(
        {
            "feature_name": [c for c in auto_frame.columns if c not in {"SK_ID_CURR", "TARGET"}],
            "feature_source": "auto",
            "feature_group": "auto_generated",
            "source_table": "entityset",
            "business_definition": "Auto-generated by Featuretools DFS.",
            "risk_direction": "unknown",
            "status": "candidate",
        }
    )
    composite_registry = pd.DataFrame(
        {
            "feature_name": [c for c in composite.columns if c != "SK_ID_CURR"],
            "feature_source": "composite",
            "feature_group": "composite",
            "source_table": "candidate_pool",
            "business_definition": "Constrained interaction or rule-cross feature. See composite_feature_spec.csv for exact formula.",
            "risk_direction": "higher_is_riskier",
            "status": "candidate",
        }
    )
    if not composite_specs.empty:
        composite_registry = composite_registry.drop(columns=["business_definition", "risk_direction"]).merge(
            composite_specs[["feature_name", "business_definition", "risk_direction"]],
            on="feature_name",
            how="left",
        )
        composite_registry["business_definition"] = composite_registry["business_definition"].fillna(
            "Constrained interaction or rule-cross feature. See composite_feature_spec.csv for exact formula."
        )
        composite_registry["risk_direction"] = composite_registry["risk_direction"].fillna("higher_is_riskier")

    registry = pd.concat([auto_registry, semantic_result.registry, composite_registry], ignore_index=True).drop_duplicates(
        subset=["feature_name"], keep="first"
    )
    registry.to_csv(registry_dir / "feature_registry.csv", index=False)

    summary = {
        "sample_size": sample_size,
        "max_depth": max_depth,
        "auto_feature_count": int(len(auto_registry)),
        "semantic_feature_count": int(len(semantic_result.registry)),
        "composite_feature_count": int(len(composite_registry)),
        "candidate_pool_shape": list(merged.shape),
    }
    (candidate_dir / "candidate_pool_summary.json").write_text(json.dumps(summary, indent=2, ensure_ascii=False))
    (candidate_dir / "candidate_pool_summary.md").write_text(
        "# Candidate Pool Summary\n\n"
        f"- sample_size: {sample_size}\n"
        f"- max_depth: {max_depth}\n"
        f"- auto_feature_count: {summary['auto_feature_count']}\n"
        f"- semantic_feature_count: {summary['semantic_feature_count']}\n"
        f"- composite_feature_count: {summary['composite_feature_count']}\n"
        f"- candidate_pool_shape: {tuple(summary['candidate_pool_shape'])}\n"
    )
    return summary


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build dual-engine candidate pool.")
    parser.add_argument("--sample-size", type=int, default=3000)
    parser.add_argument("--max-depth", type=int, default=2)
    args = parser.parse_args()
    run_candidate_pool(sample_size=args.sample_size, max_depth=args.max_depth)
